<link rel="stylesheet" type="text/css" href="model/css/core/style_core.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/semantic.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/accordion.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/ad.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/breadcrumb.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/button.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/card.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/checkbox.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/comment.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/container.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/dimmer.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/divider.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/dropdown.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/embed.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/feed.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/flag.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/form.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/grid.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/header.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/icon.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/image.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/input.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/item.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/label.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/list.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/loader.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/message.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/modal.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/nag.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/popup.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/progress.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/rail.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/rating.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/reset.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/reveal.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/search.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/segment.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/shape.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/sidebar.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/site.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/statistic.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/step.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/sticky.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/tab.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/table.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/transition.min.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/video.min.css">

<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/accordion.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/breadcrumb.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/button.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/card.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/checkbox.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/comment.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/container.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/dimmer.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/divider.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/dropdown.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/embed.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/feed.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/flag.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/form.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/grid.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/header.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/icon.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/image.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/input.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/item.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/label.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/list.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/loader.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/message.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/modal.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/nag.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/popup.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/progress.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/rail.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/rating.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/reset.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/reveal.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/search.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/segment.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/shape.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/sidebar.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/site.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/statistic.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/step.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/sticky.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/tab.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/table.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/transition.css">
<link rel="stylesheet" type="text/css" href="model/Framework/Semantic-UI-CSS-master/components/video.css">
